[project]
name = "repl-nix-healthriskanalyzer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.1",
    "plotly>=5.24.1",
    "scikit-learn>=1.6.0",
    "streamlit>=1.41.1",
]
